DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS app_installations;
DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhook_subscriptions;
DROP TABLE IF EXISTS app_credentials;
DROP TABLE IF EXISTS app_scopes;
DROP TABLE IF EXISTS app_extensions;
ALTER TABLE IF EXISTS apps DROP CONSTRAINT IF EXISTS apps_active_version_fk;
DROP TABLE IF EXISTS app_versions;
DROP TABLE IF EXISTS apps;
DROP TABLE IF EXISTS organization_memberships;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organizations;
